/*
 * This file is generated by jOOQ.
 */
package com.danjitalk.danjitalk.infrastructure.jooq.table;


import com.danjitalk.danjitalk.infrastructure.jooq.table.tables.Feed;
import com.danjitalk.danjitalk.infrastructure.jooq.table.tables.Reaction;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.feed</code>.
     */
    public static final Feed FEED = Feed.FEED;

    /**
     * The table <code>test.reaction</code>.
     */
    public static final Reaction REACTION = Reaction.REACTION;
}
