/*
 * This file is generated by jOOQ.
 */
package com.danjitalk.danjitalk.infrastructure.jooq.table;


import com.danjitalk.danjitalk.infrastructure.jooq.table.tables.Feed;
import com.danjitalk.danjitalk.infrastructure.jooq.table.tables.Reaction;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.feed</code>.
     */
    public final Feed FEED = Feed.FEED;

    /**
     * The table <code>test.reaction</code>.
     */
    public final Reaction REACTION = Reaction.REACTION;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Feed.FEED,
            Reaction.REACTION
        );
    }
}
